apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secret
  namespace: shared-gateway
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cloudflare-token
      property: api-key
      metadataPolicy: None
    secretKey: api-key
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cloudflare-token
      property: email
      metadataPolicy: None
    secretKey: email
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudflare-secret
