---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.4.0/kubevirt-operator.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.61.1/cdi-operator.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.61.1/cdi-cr.yaml
  - kubevirt-cr.yaml
patches:
- target:
    kind: Service
    name: cdi-uploadproxy
    namespace: cdi
  patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: cdi-uploadproxy
      namespace: cdi
    spec:
      type: LoadBalancer
