apiVersion: ceph.rook.io/v1
kind: CephFilesystemSubVolumeGroup
metadata:
  name: ceph-filesystem-csi
  namespace: rook-ceph
spec:
  name: csi
  filesystemName: ceph-filesystem
  pinning:
    distributed: 1
