apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secret
  namespace: external-dns
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cloudflare-token/api-key
      metadataPolicy: None
    secretKey: api-key
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cloudflare-token/email
      metadataPolicy: None
    secretKey: email
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudflare-secret
