apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp
spec:
  provider:
    gcpsm:
      projectID: homelab-a70a4db3c74cf8cd
      auth:
        workloadIdentityFederation:
          audience: //iam.googleapis.com/projects/285407169922/locations/global/workloadIdentityPools/homelab/providers/k8s-oidc
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
