apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      auth:
        serviceAccountSecretRef:
          key: token
          name: onepassword-connect-token
          namespace: external-secrets
      vault: kubernetes
