install_list:
    - argocd
    - cdi
    - ceph-csi-drivers
    - cert-manager
    - cilium
    - external-dns
    - external-secrets
    - kube-state-metrics
    - kubelet-serving
    - kubevirt
    - kyverno
    - local-path
    - metrics-server
    - multus
    - ollama
    - opentelemetry-collector
    - perses-operator
    - pipelines-as-code
    - rook-ceph
    - rook-ceph-cluster
    - shared-gateway
    - spegel
    - spire
    - spire-crds
    - tekton-chains
    - tekton-pipelines
    - velero
    - victoria-logs
    - victoria-metrics
    - vpa
    - zot
versions:
    argocd: v3.5.2
    cdi: v1.66.1
    ceph-csi-drivers: 1.0.4
    cert-manager: 1.21.1
    cilium: 1.20.1
    external-dns: 1.21.1
    external-secrets: 2.10.0
    kube-state-metrics: 8.4.2
    kubelet-serving: v0.12.0
    kubevirt: v1.9.0
    kyverno: 3.9.0
    local-path: v0.0.37
    metrics-server: v0.9.0
    multus: v4.3.0
    ollama: 1.79.0
    opentelemetry-collector: 0.172.1
    perses-operator: 0.5.0
    pipelines-as-code: v0.50.0
    rook-ceph: v1.20.2
    rook-ceph-cluster: v1.20.2
    shared-gateway: v1.6.2
    spegel: 0.7.4
    spire: 0.30.1
    spire-crds: 0.6.1
    tekton-chains: v0.29.0
    tekton-pipelines: v1.15.1
    velero: 12.1.0
    victoria-logs: 0.13.9
    victoria-metrics: 0.46.0
    vpa: 5.0.1
    zot: 0.1.124
