---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: vpa-recommender
  namespace: vpa
  labels:
    app.kubernetes.io/name: vpa
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/version: "1.7.1"
    app.kubernetes.io/component: recommender
