operator:
  replicas: 1

k8sServiceHost: localhost
k8sServicePort: 7445
debug:
  verbose: ""

cgroup:
  hostRoot: /sys/fs/cgroup
  autoMount:
    enabled: false

ipam:
  mode: kubernetes

l2announcements:
  enabled: true
  leaseDuration: 3s
  leaseRenewDeadline: 1s
  leaseRetryPeriod: 200ms

k8sClientRateLimit:
  qps: 100
  burst: 200

gatewayAPI:
  enabled: true

kubeProxyReplacement: true

cni:
  exclusive: false

securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
