operator:
  replicas: 1

k8sServiceHost: 10.0.0.5
k8sServicePort: 6443
debug:
  verbose: ""

cgroup:
  hostRoot: /sys/fs/cgroup
  autoMount:
    enabled: false

ipam:
  mode: kubernetes


gatewayAPI:
  enabled: true
  externalTrafficPolicy: Local
  hostNetwork:
    enabled: true

envoy:
  enabled: true
  securityContext:
    privileged: true
    capabilities:
      keepCapNetBindService: true
      envoy:
      - NET_BIND_SERVICE
      - CAP_SYS_ADMIN
      - CAP_BPF


kubeProxyReplacement: true

securityContext:
  privileged: true
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
