apps:

  # --- URL Based ---
  multus:
    type: url
    url: "https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/${VERSION}/deployments/multus-daemonset-thick.yml"
    namespace: kube-system
    create_namespace: false
    github_repo: "k8snetworkplumbingwg/multus-cni"

  kubevirt:
    type: url
    url: "https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-operator.yaml"
    namespace: kubevirt
    create_namespace: true
    github_repo: "kubevirt/kubevirt"

  cdi:
    type: url
    url: "https://github.com/kubevirt/containerized-data-importer/releases/download/${VERSION}/cdi-operator.yaml"
    namespace: cdi
    create_namespace: true
    github_repo: "kubevirt/containerized-data-importer"

  local-path:
    type: url
    url: "https://raw.githubusercontent.com/rancher/local-path-provisioner/refs/tags/${VERSION}/deploy/local-path-storage.yaml"
    namespace: local-path-storage
    create_namespace: true
    github_repo: "rancher/local-path-provisioner"

  metrics-server:
    type: url
    url: "https://github.com/kubernetes-sigs/metrics-server/releases/download/${VERSION}/components.yaml"
    namespace: kube-system
    github_repo: "kubernetes-sigs/metrics-server"

  kubelet-serving:
    type: url
    url: "https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/${VERSION}/deploy/standalone-install.yaml"
    namespace: kubelet-serving-cert-approver
    create_namespace: true
    github_repo: "alex1989hu/kubelet-serving-cert-approver"

  argocd:
    type: url
    url: "https://raw.githubusercontent.com/argoproj/argo-cd/${VERSION}/manifests/install.yaml"
    namespace: argocd
    create_namespace: true
    github_repo: "argoproj/argo-cd"

  shared-gateway:
    type: url
    url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/${VERSION}/experimental-install.yaml"
    namespace: shared-gateway
    create_namespace: true
    github_repo: "kubernetes-sigs/gateway-api"

  pipelines-as-code:
    type: url
    url: "https://github.com/openshift-pipelines/pipelines-as-code/releases/download/${VERSION}/release.k8s.yaml"
    namespace: pipelines-as-code
    create_namespace: true
    github_repo: "openshift-pipelines/pipelines-as-code"

  tekton-pipelines:
    type: url
    url: "https://github.com/tektoncd/pipeline/releases/download/${VERSION}/release.yaml"
    namespace: tekton-pipelines
    create_namespace: true
    github_repo: "tektoncd/pipeline"
    kustomize_namespace: false

  # --- Helm Based ---
  spegel:
    type: helm
    repo_name: spegel
    repo_url: oci://ghcr.io/spegel-org/helm-charts/spegel
    chart: spegel
    namespace: spegel
    create_namespace: true

  ollama:
    type: helm
    repo_name: otwld
    repo_url: https://helm.otwld.com/
    chart: ollama
    namespace: ollama
    create_namespace: true

  cert-manager:
    type: helm
    repo_name: jetstack
    repo_url: "oci://quay.io/jetstack/charts/cert-manager"
    chart: cert-manager
    namespace: cert-manager
    create_namespace: true
    kustomize_namespace: false

  external-dns:
    type: helm
    repo_name: external-dns
    repo_url: "https://kubernetes-sigs.github.io/external-dns/"
    chart: external-dns
    namespace: external-dns
    create_namespace: true

  rook-ceph:
    type: helm
    repo_name: rook-release
    repo_url: "https://charts.rook.io/release"
    chart: rook-ceph
    namespace: rook-ceph
    kustomize_namespace: false
    create_namespace: true

  rook-ceph-cluster:
    type: helm
    repo_name: rook-release
    repo_url: "https://charts.rook.io/release"
    chart: rook-ceph-cluster
    namespace: rook-ceph
    kustomize_namespace: false
    create_namespace: false

  ceph-csi-drivers:
    type: helm
    repo_name: ceph-csi-operator
    repo_url: "https://ceph.github.io/ceph-csi-operator"
    chart: ceph-csi-drivers
    namespace: rook-ceph
    kustomize_namespace: false
    create_namespace: false

  cilium:
    type: helm
    repo_name: cilium
    repo_url: "oci://quay.io/cilium/charts/cilium"
    chart: cilium
    namespace: kube-system
    kustomize_namespace: false
    create_namespace: false

  opentelemetry-collector:
    type: helm
    repo_name: opentelemetry
    repo_url: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    chart: opentelemetry-collector
    namespace: opentelemetry
    create_namespace: true

  external-secrets:
    type: helm
    repo_name: external-secrets
    repo_url: "https://charts.external-secrets.io"
    chart: external-secrets
    namespace: external-secrets
    create_namespace: true

  perses-operator:
    type: helm
    repo_name: perses
    repo_url: https://perses.github.io/helm-charts
    chart: perses-operator
    namespace: perses
    create_namespace: false

  victoria-metrics:
    type: helm
    repo_name: vm
    repo_url: "https://victoriametrics.github.io/helm-charts"
    chart: victoria-metrics-single
    namespace: victoria-metrics
    create_namespace: true

  victoria-logs:
    type: helm
    repo_name: vm
    repo_url: "https://victoriametrics.github.io/helm-charts"
    chart: victoria-logs-single
    namespace: victoria-logs
    create_namespace: true

  kube-state-metrics:
    type: helm
    repo_name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"
    chart: kube-state-metrics
    namespace: kube-state-metrics
    create_namespace: true

  kyverno:
    type: helm
    repo_name: kyverno
    repo_url: "https://kyverno.github.io/kyverno/"
    chart: kyverno
    namespace: kyverno
    create_namespace: true

  spire-crds:
    type: helm
    repo_name: spire
    repo_url: "https://spiffe.github.io/helm-charts-hardened/"
    chart: spire-crds
    namespace: spire-system
    create_namespace: true

  spire:
    type: helm
    repo_name: spire
    repo_url: "https://spiffe.github.io/helm-charts-hardened/"
    chart: spire
    namespace: spire-system
    create_namespace: true

  velero:
    type: helm
    repo_name: vmware-tanzu
    repo_url: "https://vmware-tanzu.github.io/helm-charts"
    chart: velero
    namespace: velero
    create_namespace: true

  tekton-chains:
    type: url
    url: "https://github.com/tektoncd/chains/releases/download/${VERSION}/release.yaml"
    namespace: tekton-chains
    create_namespace: true
    github_repo: "tektoncd/chains"

  zot:
    type: helm
    repo_name: zot
    repo_url: "https://zotregistry.dev/helm-charts/"
    chart: zot
    namespace: zot
    create_namespace: true

  vpa:
    type: helm
    repo_name: fairwinds
    repo_url: "https://charts.fairwinds.com/stable"
    chart: vpa
    namespace: vpa
    create_namespace: true
