---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - policy.yaml
  - ippool.yaml

helmCharts:
- name: cilium
  namespace: kube-system
  releaseName: cilium
  version: 1.17.1
  repo: https://helm.cilium.io/
  includeCRDs: true
  skipHooks: false
  skipTests: false
  valuesFile: values.yaml
