operatorNamespace: rook-ceph
cephObjectStores:
  - name: rgw-store
    spec:
      metadataPool:
        failureDomain: host
        replicated:
          size: 3
      dataPool:
        failureDomain: host
        erasureCoded:
          dataChunks: 2
          codingChunks: 1
        parameters:
          bulk: "true"
      preservePoolsOnDelete: true
      gateway:
        port: 80
        resources:
          limits:
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1Gi"
        instances: 1
        priorityClassName: system-cluster-critical
    storageClass:
      enabled: false
toolbox:
  enabled: true
cephBlockPoolsVolumeSnapshotClass:
  enabled: true
cephFileSystemVolumeSnapshotClass:
  enabled: true
