operatorNamespace: rook-ceph
cephObjectStores: []
toolbox:
  enabled: true
cephBlockPoolsVolumeSnapshotClass:
  enabled: true
cephFileSystemVolumeSnapshotClass:
  enabled: true
#cephClusterSpec:
#  annotations:
#    all:
#      kubernetes.io/egress-bandwidth: "60M"
#      kubernetes.io/ingress-bandwidth: "60M"
