---
apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/component: kube-rbac-proxy
        app.kubernetes.io/created-by: perses-operator
        app.kubernetes.io/instance: controller-manager-metrics-service
        app.kubernetes.io/name: perses-operator
        app.kubernetes.io/part-of: perses-operator
        control-plane: controller-manager
    name: perses-operator-controller-manager-metrics-service
    namespace: perses
spec:
    ports:
        - name: https
          port: 8082
          protocol: TCP
          targetPort: https
    selector:
        control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/name: perses-operator
        app.kubernetes.io/instance: perses-operator
    name: perses-operator-webhook-service
    namespace: perses
spec:
    ports:
        - port: 443
          protocol: TCP
          targetPort: 9443
    selector:
        control-plane: controller-manager
