apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/clusterrole-multus.yaml
- base/clusterrolebinding-multus.yaml
- base/configmap-multus-daemon-config.yaml
- base/customresourcedefinition-network-attachment-definitions.k8s.cni.cncf.io.yaml
- base/daemonset-kube-multus-ds.yaml
- base/serviceaccount-multus.yaml
- overlay/networkattachmentdefinition-macvlan-conf.yaml
