operator:
  replicas: 1
  prometheus:
    enabled: true
k8sServiceHost: localhost
k8sServicePort: 7445
debug:
  enabled: true
cgroup:
  hostRoot: /sys/fs/cgroup
  autoMount:
    enabled: false
ipam:
  mode: kubernetes
l2announcements:
  enabled: true
  leaseDuration: 3s
  leaseRenewDeadline: 1s
  leaseRetryPeriod: 200ms
k8sClientRateLimit:
  qps: 100
  burst: 200
bandwidthManager:
  enabled: true
  bbr: true
gatewayAPI:
  enabled: true
  gatewayClass:
    create: "true"
kubeProxyReplacement: true
cni:
  exclusive: false
prometheus:
  enabled: true
encryption:
  enabled: true
  type: wireguard
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
hubble:
  enabled: true
  tls:
    enabled: true
    auto:
      enabled: true
      method: certmanager
      certValidityDuration: 1095
      certManagerIssuerRef:
        group: cert-manager.io
        kind: Issuer
        name: hubble-ca-issuer
  relay:
    enabled: true
    prometheus:
      enabled: true
  metrics:
    enabled:
      - dns:query:ignoreAAAA
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    port: 9965
  ui:
    enabled: true
