---
apiVersion: v1
kind: ConfigMap
metadata:
  name: perses
  labels:
    app.kubernetes.io/name: perses
    app.kubernetes.io/instance: perses
    app.kubernetes.io/version: v0.53.1
    app.kubernetes.io/part-of: perses
    app.kubernetes.io/component: configuration
data:
  config.yaml: |-

    api_prefix: ""
    database:
      file:
        extension: json
        folder: /perses
    frontend:
      explorer:
        enable: true
      important_dashboards: []
      information: ""
    provisioning:
      folders:
      - /etc/perses/provisioning
      interval: 10m
    security:
      cookie:
        same_site: lax
        secure: false
      enable_auth: false
      readonly: false
