---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: perses
  labels:
    app.kubernetes.io/name: perses
    app.kubernetes.io/instance: perses
    app.kubernetes.io/version: v0.53.1
    app.kubernetes.io/part-of: perses
    app.kubernetes.io/component: iam
