---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spegel
  namespace: spegel
  labels:
    app.kubernetes.io/component: spegel
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
    app.kubernetes.io/version: "v0.7.4"
spec:
  revisionHistoryLimit: 10
  updateStrategy:
    {}
  selector:
    matchLabels:
      app.kubernetes.io/component: spegel
      app.kubernetes.io/name: spegel
      app.kubernetes.io/instance: spegel
  template:
    metadata:
      labels:
        app.kubernetes.io/component: spegel
        app.kubernetes.io/name: spegel
        app.kubernetes.io/instance: spegel
    spec:
      serviceAccountName: spegel
      securityContext:
        {}
      priorityClassName: system-node-critical
      initContainers:
      - name: configuration
        image: "ghcr.io/spegel-org/spegel@sha256:26c60b05e08ac738e8442bc389c5780bff0e1d8153956e45d810a2f1008cf56f"
        imagePullPolicy: IfNotPresent
        securityContext:
            readOnlyRootFilesystem: true
        args:
          - configuration
          - --log-level=INFO
          - --containerd-registry-config-path=/etc/cri/conf.d/hosts
          - --mirror-targets
          - http://$(NODE_IP):30020
          - http://$(NODE_IP):30021
          - --resolve-tags=true
          - --prepend-existing=false
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 128Mi
        volumeMounts:
          - name: containerd-config
            mountPath: /etc/cri/conf.d/hosts
      containers:
      - name: registry
        image: "ghcr.io/spegel-org/spegel@sha256:26c60b05e08ac738e8442bc389c5780bff0e1d8153956e45d810a2f1008cf56f"
        imagePullPolicy: IfNotPresent
        securityContext:
            readOnlyRootFilesystem: true
        args:
          - registry
          - --log-level=INFO
          - --mirror-resolve-retries=3
          - --mirror-resolve-timeout=20ms
          - --registry-addr=:5000
          - --router-addr=:5001
          - --metrics-addr=:9090
          - --containerd-sock=/run/containerd/containerd.sock
          - --containerd-namespace=k8s.io
          - --bootstrap-kind=dns
          - --dns-bootstrap-domain=spegel-bootstrap.spegel.svc.cluster.local.
          - --containerd-content-path=/var/lib/containerd/io.containerd.content.v1.content
          - --debug-web-enabled=true
          - --data-dir=/var/lib/spegel
        env:
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
              divisor: 1
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
          - name: registry
            containerPort: 5000
            hostPort: 30020
            protocol: TCP
          - name: router-tcp
            containerPort: 5001
            protocol: TCP
          - name: router-quic
            containerPort: 5001
            protocol: UDP
          - name: metrics
            containerPort: 9090
            protocol: TCP
        # Startup may take a bit longer on bootsrap as Pods need to find each other.
        # This is why the startup proben is a bit more forgiving, while hitting the endpoint more often.
        startupProbe:
          periodSeconds: 3
          failureThreshold: 60
          httpGet:
            path: /readyz
            port: registry
        readinessProbe:
          httpGet:
            path: /readyz
            port: registry
        volumeMounts:
          - name: spegel-data
            mountPath: /var/lib/spegel
          - name: containerd-sock
            mountPath: /run/containerd/containerd.sock
          - name: containerd-content
            mountPath: /var/lib/containerd/io.containerd.content.v1.content
            readOnly: true
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 128Mi
      volumes:
        - name: spegel-data
          hostPath:
            path: /var/lib/spegel
            type: DirectoryOrCreate
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
        - name: containerd-content
          hostPath:
            path: /var/lib/containerd/io.containerd.content.v1.content
            type: Directory
        - name: containerd-config
          hostPath:
            path: /etc/cri/conf.d/hosts
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
