---
apiVersion: v1
kind: Pod
metadata:
  name: spegel-cleanup-wait
  namespace: spegel
  labels:
    app.kubernetes.io/component: cleanup-wait
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
    app.kubernetes.io/version: "v0.7.4"
  annotations:
    helm.sh/hook: "post-delete"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook-weight: "1"
spec:
  containers:
    - name: cleanup-wait
      image: "ghcr.io/spegel-org/spegel@sha256:26c60b05e08ac738e8442bc389c5780bff0e1d8153956e45d810a2f1008cf56f"
      imagePullPolicy: IfNotPresent
      args:
        - cleanup-wait
        - --probe-endpoint=spegel-cleanup.spegel.svc.cluster.local.:8080
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
