---
apiVersion: v1
kind: Service
metadata:
  name: spegel-cleanup
  namespace: spegel
  labels:
    app.kubernetes.io/component: cleanup
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
    app.kubernetes.io/version: "v0.7.4"
  annotations:
    helm.sh/hook: "post-delete"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook-weight: "0"
spec:
  selector:
    app.kubernetes.io/component: cleanup
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: readiness
      port: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: spegel
  namespace: spegel
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
    app.kubernetes.io/version: "v0.7.4"
spec:
  selector:
    app.kubernetes.io/component: spegel
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: spegel-registry
  namespace: spegel
  labels:
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
    app.kubernetes.io/version: "v0.7.4"
  annotations:
    service.kubernetes.io/topology-mode: "auto"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: spegel
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
  ports:
    - name: registry
      port: 5000
      targetPort: registry
      nodePort: 30021
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: spegel-bootstrap
  namespace: spegel
  labels:
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
    app.kubernetes.io/version: "v0.7.4"
spec:
  selector:
    app.kubernetes.io/component: spegel
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
  clusterIP: None
  publishNotReadyAddresses: true
