---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spegel
  namespace: spegel
  labels:
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
    app.kubernetes.io/version: "v0.7.4"
