apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/talos/0.30.1
patches:
  - path: patches/agent-daemonset-tolerations.yaml
  - path: patches/csi-daemonset-tolerations.yaml
