apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: perses-github-oauth
  namespace: perses
  labels:
    perses.dev/watch: "true"
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: homelab-app-secrets
      property: perses-github-client-id
      metadataPolicy: None
    secretKey: client-id
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: homelab-app-secrets
      property: perses-github-client-secret
      metadataPolicy: None
    secretKey: client-secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: perses-github-oauth
