apiVersion: v1
kind: Service
metadata:
  name: cdi-uploadproxy-lb
  namespace: cdi
  labels:
    cdi.kubevirt.io: "cdi-uploadproxy"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cdi-uploadproxy.nhlabs.org
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
