apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp1s0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.0.0/24",
        "rangeStart": "10.0.0.200",
        "rangeEnd": "10.0.0.220",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.0.0.1",
        "dns": "10.0.0.1"
      }
    }'
