apiVersion: v1
data:
  config.yaml: |
    apiVersion: controller.config.cert-manager.io/v1alpha1
    enableGatewayAPI: true
    kind: ControllerConfiguration
kind: ConfigMap
metadata:
  labels:
    app: cert-manager
  name: cert-manager
