apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-gcp-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp
    kind: ClusterSecretStore
  target:
    name: velero-gcp-credentials
    creationPolicy: Owner
  data:
    - secretKey: credentials
      remoteRef:
        key: velero-gcp-sa-key
