apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/v1.66.1
  - ../../resources
  - resources
patches:
  - path: patches/crd-annotation.yaml
  - path: patches/patch-namespace.yaml
