---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spire-system-spire-default
  labels:
    spire.spiffe.io/class-name: spire-system-spire
spec:
  className: "spire-system-spire"
  hint: default
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}"
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - spire-system
  fallback: true
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spire-system-spire-oidc-discovery-provider
  labels:
    spire.spiffe.io/class-name: spire-system-spire
spec:
  className: "spire-system-spire"
  hint: oidc-discovery-provider
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}"
  podSelector:
    matchLabels:
      component: oidc-discovery-provider
      release: spire
      release-namespace: spire-system
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - spire-system
  dnsNameTemplates:
    - oidc-discovery.{{ .TrustDomain }}
  autoPopulateDNSNames: true
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spire-system-spire-test-keys
  labels:
    spire.spiffe.io/class-name: spire-system-spire
spec:
  className: "spire-system-spire"
  hint: test-keys
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}"
  podSelector:
    matchLabels:
      component: test-keys
      release: spire
      release-namespace: spire-system
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - spire-system
