---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/version: "0.33.2"
  name: ollama
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  volumeMode: "Filesystem"
  resources:
    requests:
      storage: "15Gi"
