# Source: connect/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onepassword-connect-operator
  labels:
    helm.sh/chart: connect-1.17.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: connect
    app.kubernetes.io/version: "1.7.3"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: onepassword-connect-operator
  namespace: connect
roleRef:
  kind: ClusterRole
  name: onepassword-connect-operator
  apiGroup: rbac.authorization.k8s.io
