apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
- name: connect
  namespace: connect
  releaseName: connect
  version: 1.17.0
  repo: https://1password.github.io/connect-helm-charts
  includeCRDs: true
  skipHooks: true
  skipTests: true
  valuesInline:
    operator:
      create: true
