---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: connect
helmCharts:
- name: connect
  namespace: connect
  releaseName: connect
  version: 1.16.0
  repo: https://1password.github.io/connect-helm-charts
  includeCRDs: true
  valuesInline:
    connect:
      applicationName: connect
    operator:
      create: true
