apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole-onepassword-connect-operator.yaml
- clusterrolebinding-onepassword-connect-operator.yaml
- customresourcedefinition-onepassworditems.onepassword.com.yaml
- deployment-onepassword-connect-operator.yaml
- deployment-onepassword-connect.yaml
- service-onepassword-connect.yaml
- serviceaccount-onepassword-connect-operator.yaml
