# Source: connect/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onepassword-connect-operator
  namespace: connect
  labels:
    helm.sh/chart: connect-1.17.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: connect
    app.kubernetes.io/version: "1.7.3"
    app.kubernetes.io/managed-by: Helm
